ClubHVNH/ClubHVNH/Models/Member.cs
namespace ClubHVNH.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Member")]
    public partial class Member
    {
        [Display(Name = "Mã sinh viên")]
        [StringLength(50)]
        public string Id { get; set; }

        [Display(Name = "Họ và tên")]
        [StringLength(250)]
        public string Name { get; set; }

        [Display(Name = "Ngày sinh")]
        [StringLength(50)]
        public string DateOfBirth { get; set; }

        [Display(Name = "Lớp")]
        [StringLength(50)]
        public string Class { get; set; }

        [Display(Name = "Khoa")]
        [StringLength(250)]
        public string Major { get; set; }

        [Display(Name = "SĐT")]
        [StringLength(50)]
        public string Phone { get; set; }

        [StringLength(50)]
        public string Email { get; set; }
    }
}

ClubHVNH/ClubHVNH/Models/ViewModel/MemberViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ClubHVNH.Models.ViewModel
{
    public class MemberViewModel
    {
        [Display(Name = "Mã sinh viên")]
        public string Id { get; set; }

        [Display(Name = "Họ và tên")]
        public string Name { get; set; }

        [Display(Name = "Ngày sinh")]
        public string DateOfBirth { get; set; }

        [Display(Name = "Lớp")]
        public string Class { get; set; }

        [Display(Name = "Khoa")]       
        public string Major { get; set; }

        [Display(Name = "SĐT")]        
        public string Phone { get; set; }
       
        public string Email { get; set; }

        [Display(Name = "Ngày tham gia")]
        public DateTime? CreatedDate { get; set; }

        [Display(Name = "Tên ban")]
        public string DepartmentName { get; set; }

        [Display(Name = "Chức vụ")]
        public string RankName { get; set; }

        public long? RankId { get; set; }

        [Display(Name = "Số lần đã huy động")]
        public int NumberOfJoinProgram { get; set; }
    }
}

ClubHVNH/ClubHVNH/Controllers/MembersController.cs
using ClubHVNH.Models;
using ClubHVNH.Models.ViewModel;
using ClubHVNH.Services.Interfaces;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ClubHVNH.Controllers
{
    [AuthorizeUser(AccessLevel = "CLB")]
    public class MembersController : Controller
    {
        private ClubManagementDbContext db = new ClubManagementDbContext();
        private readonly IMemberService memberService;

        //inject dependency
        public MembersController(IMemberService memberService)
        {
            this.memberService = memberService;
        }

        // GET: Members
        public ActionResult Index(int? page)
        {
            var clubid = (long)Session["clubid"];

            // 1. Tham số int? dùng để thể hiện null và kiểu int
            // page có thể có giá trị là null và kiểu int.

            // 2. Nếu page = null thì đặt lại là 1.
            if (page == null) page = 1;

            // 3. Tạo truy vấn, lưu ý phải sắp xếp theo trường nào đó, ví dụ OrderBy
            // theo LinkID mới có thể phân trang.
            var list = memberService.GetMembersList(clubid);

            // 4. Tạo kích thước trang (pageSize) hay là số Link hiển thị trên 1 trang
            int pageSize = 7;

            // 4.1 Toán tử ?? trong C# mô tả nếu page khác null thì lấy giá trị page, còn
            // nếu page = null thì lấy giá trị 1 cho biến pageNumber.
            int pageNumber = (page ?? 1);

            return View(list.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Create()
        {
            //Get clubId from Session
            var clubid = (long)Session["clubid"];

            ViewBag.RankId = new SelectList(db.Ranks.Where(r => r.ClubId == clubid), "Id", "Name");
            ViewBag.DepartmentId = new SelectList(db.Departments.Where(r => r.ClubId == clubid), "Id", "Name");

            return View();
        }

        [HttpPost]
        public JsonResult GetAutoCompleteSearch(string Prefix)
        {

            var memberList = memberService.GetMemberByPrefix(Prefix);

            return Json(memberList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetSearchingData(string SearchValue)
        {

            var memberList = memberService.GetMemberById(SearchValue);

            return Json(memberList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult InsertMembers(List<JoinClub> members)
        {
            //Get clubId from Session
            var clubid = (long)Session["clubid"];
            string message = "ok";

            //Check for NULL.
            if (members == null)
            {
                members = new List<JoinClub>();
            }

            //Loop and insert records.
            foreach (var member in members)
            {
                var memberExist = db.JoinClubs.Find(member.MemberId, clubid);
                var memberIsValid = db.Members.Find(member.MemberId);

                if(memberExist != null)
                {
                    message = member.MemberId;
                    break;
                }

                if(memberIsValid == null)
                {
                    message = member.MemberId;
                    break;
                }

                member.CreatedDate = DateTime.Now;
                member.ClubId = clubid;
                               
                db.JoinClubs.Add(member);
            }

            db.SaveChanges();

            return Json(message);

        }

        // GET: Members/Details/19A4040xxx
        public ActionResult Details(string id)
        {
            //Get clubId from Session
            var clubid = (long)Session["clubid"];

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var member = memberService.GetMembersInfo(clubid, id);

            if (member == null)
            {
                return HttpNotFound();
            }

            return View(member);
        }

        // GET: Members/Delete/19A4040xxx
        public ActionResult Delete(string id)
        {
            //Get clubId from Session
            var clubid = (long)Session["clubid"];

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var member = memberService.GetMembersInfo(clubid, id);

            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/19A4040xxx
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            //Get clubId from Session
            var clubid = (long)Session["clubid"];

            JoinClub member = db.JoinClubs.Find(id, clubid);

            db.JoinClubs.Remove(member);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Members/Edit/19A4040xxx
        public ActionResult Edit(string id)
        {
            //Get clubId from Session
            var clubid = (long)Session["clubid"];

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JoinClub member = db.JoinClubs.Find(id, clubid);

            ViewBag.RankId = new SelectList(db.Ranks.Where(r => r.ClubId == clubid), "Id", "Name", member.RankId);
            ViewBag.DepartmentId = new SelectList(db.Departments.Where(r => r.ClubId == clubid), "Id", "Name", member.DepartmentId);

            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/19A4040xxx
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MemberId, DepartmentId, RankId")] string memberId, long? departmentId, long? rankId)
        {
            //Get clubId from Session
            var clubId = (long)Session["clubid"];

            if (ModelState.IsValid)
            {
                memberService.UpdateMember(memberId, clubId, departmentId, rankId);
                return RedirectToAction("Index");
            }

            return View("Edit");
        }

    }
}

ClubHVNH/ClubHVNH/Views/Members/Create.cshtml
@model ClubHVNH.Models.JoinClub
@{
    /**/

    ViewBag.Title = "Thêm mới thành viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>@Html.ActionLink("<< Quay lại danh sách", "Index", null, new { @class = "btn btn-default" })</p>

<form method="post" id="insert_form">
    <div class="table-responsive">
        <span id="error"></span>
        <table id="tblMembers" class="table">
            <thead>
                <tr>
                    <th>Mã sinh viên</th>
                    <th>Họ và tên</th>
                    <th>Ngày sinh</th>
                    <th>Lớp</th>
                    <th>Khoa</th>
                    <th>Ban</th>
                    <th>Chức vụ</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="item_table"></tbody>
            <tfoot>
                <tr>
                    <td><input type="text" id="txtId" name="txtId" class="form-control" /></td>
                    <td><input type="text" id="txtName" name="txtName" class="form-control" disabled /></td>
                    <td><input type="text" id="txtDateOfBirth" name="txtDateOfBirth" class="form-control" disabled /></td>
                    <td><input type="text" id="txtClass" name="txtClass" class="form-control" disabled /></td>
                    <td><input type="text" id="txtMajor" name="txtMajor" class="form-control" disabled /></td>
                    <td>@Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })</td>
                    <td>@Html.DropDownList("RankId", null, htmlAttributes: new { @class = "form-control" })</td>
                    <td><input type="button" id="btnAdd" value="Thêm mới" class="btn btn-success" /></td>
                </tr>
            </tfoot>
        </table>
    </div>
</form>

<br />

<input type="button" id="btnSave" value="Lưu tất cả" class="btn btn-warning"/>

<button class="btn btn-warning loading" type="button" disabled style="display:none;">
    <span class="glyphicon glyphicon-refresh"></span>
    Đang lưu...
</button>

@*Scripts file that help to make scroll bar in auto complete search box*@
<script  type="text/javascript" src="~/Scripts/jquery.ui.autocomplete.scroll.min.js"></script>

<script type="text/javascript">

    //Show suggest list of MemberId when we type on #txtId textbox
    $("#txtId").autocomplete({
        maxShowItems: 8,
        source: function (request, response) {
            $.ajax({
                url: '@Url.Action("GetAutoCompleteSearch", "Members")',
                type: "POST",
                dataType: "json",
                data: { Prefix: request.term },
                success: function (data) {
                    response($.map(data, function (item) {
                        return { label: item.Id + " - " + item.Name, value: item.Id, data: item };

                    }));
                }
            });
        },

        select: function (e, ui) {

            alert("selected!");

        }
    });

    $("body").on("click", "#btnAdd", function () {

        var error = '';
        $('#txtName').each(function () {
            if ($(this).val() == '') {

                error += "<p>Hãy nhập thông tin</p>";

                return false;
            }
        });

        if (error == '') {
            //Reference the Name and Country TextBoxes.
            var Id = $("#txtId");
            var Name = $("#txtName");
            var DateOfBirth = $("#txtDateOfBirth");
            var Class = $("#txtClass");
            var Major = $("#txtMajor");
            var DepartmentId = $("#DepartmentId");
            var RankId = $("#RankId");
            var DepartmentName = $("#DepartmentId option:selected");
            var RankName = $("#RankId option:selected");
            
            var html = '';
            html += '<tr>';
            html += '<td>' + Id.val() + '</td>';
            html += '<td>' + Name.val() + '</td>';
            html += '<td>' + DateOfBirth.val() + '</td>';
            html += '<td>' + Class.val() + '</td>';
            html += '<td>' + Major.val() + '</td>';
            html += '<td style="display:none">' + DepartmentId.val() + '</td>';
            html += '<td style="display:none">' + RankId.val() + '</td>';
            html += '<td>' + DepartmentName.text() + '</td>';
            html += '<td>' + RankName.text() + '</td>';
            html += '<td><input type="button" class="btn btn-danger" onclick ="Remove(this)" value="Xóa" /></td></tr>';

            $('#item_table').append(html);

            //Clear All the TextBoxes.
            $('input[type=text]').each(function () {

                $(this).val('');

            });

        }

        else {
            alert("Hãy điền thông tin");

        }

    });

    function Remove(button) {
        //Determine the reference of the Row using the Button.
        var row = $(button).closest("TR");
        var name = $("TD", row).eq(0).html();
        if (confirm("Bạn có chắc chắn muốn xóa: " + name + "?")) {
            //Get the reference of the Table.
            var table = $("#tblMembers")[0];

            //Delete the Table row using it's Index.
            table.deleteRow(row[0].rowIndex);
        }
    };

    $("body").on("click", "#btnSave", function () {
        //Loop through the Table rows and build a JSON array.
        var members = new Array();
        $("#tblMembers TBODY TR").each(function () {
            var row = $(this);
            var member = {};

            member.MemberId = row.find("TD").eq(0).html();
            member.DepartmentId = row.find("TD").eq(5).html();
            member.RankId = row.find("TD").eq(6).html();

            members.push(member);
        });

        $('.loading').show();
        $('#btnSave').hide();

        //Send the JSON array to Controller using AJAX.
        $.ajax({
            type: "POST",
            url: '@Url.Action("InsertMembers", "Members")',
            data: JSON.stringify(members),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (message) {
                if (message == 'ok') {
                    $('.loading').hide();
                    $('#btnSave').show();

                    alert("Các thành viên đã được lưu");

                    //Empty all temp data in tbody #item_table
                    $("#item_table").empty();
                }
                else {
                    $('.loading').hide();
                    $('#btnSave').show();

                    alert("Mã sinh viên: " + message + " Đã có trong danh sách hoặc không tồn tại");
                }

            }
        });
    });

    $('#txtId').on('input change paste', function () {
        $.ajax({
            type: "post",
            url: '@Url.Action("GetSearchingData", "Members")',
            data: {
                SearchValue: $("#txtId").val()
            },
            success: function (result) {
                if ($.trim(result)) {
                    $.each(result, function (index, value) {
                        $("#txtId").val(value.Id);
                        $("#txtName").val(value.Name);
                        $("#txtDateOfBirth").val(value.DateOfBirth);
                        $("#txtClass").val(value.Class);
                        $("#txtMajor").val(value.Major);
                    });
                }
                else {

                    $("#txtName").val('');
                    $("#txtDateOfBirth").val('');
                    $("#txtClass").val('');
                    $("#txtMajor").val('');
                }
            },

            error: function () {

                $("#txtName").val('');
                $("#txtDateOfBirth").val('');
                $("#txtClass").val('');
                $("#txtMajor").val('');
            }
        });
    });

</script>

ClubHVNH/ClubHVNH/Views/Members/Delete.cshtml
@model IEnumerable<ClubHVNH.Models.ViewModel.MemberViewModel>

@{
    ViewBag.Title = "Xóa thành viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Bạn có chắc chắn muốn xóa?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        @foreach (var item in Model)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Id)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.Id)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Class)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.Class)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Major)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.Major)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Phone)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.Phone)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DepartmentName)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.DepartmentName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.RankName)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.RankName)
            </dd>
        }
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-danger" /> |
            @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-warning" })
        </div>
    }
</div>

ClubHVNH/ClubHVNH/Views/Members/Details.cshtml
@model IEnumerable<ClubHVNH.Models.ViewModel.MemberViewModel>
@{
    ViewBag.Title = "Chi tiết thành viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <dl class="dl-horizontal">
        @foreach (var item in Model)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Id)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.Id)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Class)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.Class)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Major)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.Major)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Phone)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.Phone)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DepartmentName)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.DepartmentName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.RankName)
            </dt>

            <dd>
                @Html.DisplayFor(modelItem => item.RankName)
            </dd>
        }
    </dl>
</div>

ClubHVNH/ClubHVNH/Views/Members/Edit.cshtml
@model ClubHVNH.Models.JoinClub

@{
    ViewBag.Title = "Sửa thành viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MemberId)

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-2"></div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RankId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-8">
                @Html.DropDownList("RankId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RankId, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-2"></div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<br />
<div>
    @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-warning" })
</div>

ClubHVNH/ClubHVNH/Views/Members/Index.cshtml
@model PagedList.IPagedList<ClubHVNH.Models.ViewModel.MemberViewModel>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Danh sách thành viên";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Convert.ToBoolean(Session["active"]) == true)
{
    <p>
        @Html.ActionLink("Thêm mới", "Create", null, new { @class = "btn btn-warning" })
    </p>
}

<table class="table">

    @{
        int count = 0;
    }

    <tr>
        <th>
            STT
        </th>
        <th>
            Mã sinh viên
        </th>
        <th>
            Họ và tên
        </th>
        <th>
            Ngày sinh
        </th>
        <th>
            Lớp
        </th>
        <th>
            Khoa
        </th>
        <th>
            Tên ban
        </th>
        <th>
            Chức vụ
        </th>
        <th>Thao tác</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{ count++; }
                @count
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Major)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartmentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RankName)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.Id }, new { @class = "btn btn-info" })
                @Html.ActionLink("Chi tiết", "Details", new { id = item.Id }, new { @class = "btn btn-default" })

                @if (Convert.ToBoolean(Session["active"]) == true)
                {
                    @Html.ActionLink("Xóa", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                }
            </td>
        </tr>
    }
</table>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))