ClubHVNH/ClubHVNH/Models/ViewModel/ListForRankingViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ClubHVNH.Models.ViewModel
{
    public class ListForRankingViewModel
    {
        [Display(Name = "Mã sinh viên")]
        public string Id { get; set; }

        [Display(Name = "Họ và tên")]
        public string Name { get; set; }

        [Display(Name = "Ngày sinh")]
        public string DateOfBirth { get; set; }

        [Display(Name = "Lớp")]
        public string Class { get; set; }

        [Display(Name = "Khoa")]
        public string Major { get; set; }

        [Display(Name = "SĐT")]
        public string Phone { get; set; }

        public string Email { get; set; }

        [Display(Name = "Tên ban")]
        public string DepartmentName { get; set; }

        [Display(Name = "Chức vụ")]
        public string RankName { get; set; }

        [Display(Name = "Mức độ đánh giá")]
        public string RankingCategory { get; set; }

        [Display(Name = "Điểm hệ 10")]
        public double? Mark10 { get; set; }

        [Display(Name = "Điểm hệ 4")]
        public double? Mark4 { get; set; }

    }
}

ClubHVNH/ClubHVNH/Controllers/ListForRankingController.cs
using ClubHVNH.Models;
using ClubHVNH.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClubHVNH.Controllers
{
    [AuthorizeUser(AccessLevel = "CLB")]
    public class ListForRankingController : Controller
    {
        private ClubManagementDbContext db = new ClubManagementDbContext();
        private readonly IMemberService memberService;
        private readonly IRankingService rankingService;

        //inject dependency
        public ListForRankingController(IMemberService memberService, IRankingService rankingService)
        {
            this.memberService = memberService;
            this.rankingService = rankingService;
        }

        // GET: ListForRanking
        public ActionResult Index()
        {
            var clubid = (long)Session["clubid"];
            var model = rankingService.GetRankingListView(clubid);

            return View(model);
        }

        public ActionResult Create()
        {
            var clubid = (long)Session["clubid"];
            var model = memberService.GetMembersList(clubid);

            ViewBag.RankingCategoryId = new SelectList(db.RankingCategories, "Id", "Name");

            return View(model);
        }

        [HttpPost]
        public JsonResult Create(List<RankingListDetail> rankingListDetails)
        {
            //Get clubId from Session
            var clubid = (long)Session["clubid"];

            var rankingList = new RankingList();

            long postid = Convert.ToInt32(RouteData.Values["id"]);

            string message = "ok";

            //Check for NULL.
            if (rankingListDetails == null)
            {
                rankingListDetails = new List<RankingListDetail>();
            }


            rankingList.ClubId = clubid;
            rankingList.PostId = postid;
            rankingList.RankedDate = DateTime.Now;

            db.RankingLists.Add(rankingList);
            db.SaveChanges();

            var listid = rankingList.Id;

            //Loop and insert records.
            foreach (var rankingListDetail in rankingListDetails)
            {
                var memberIsValid = db.Members.Find(rankingListDetail.MemberId);

                if (memberIsValid == null)
                {
                    message = rankingListDetail.MemberId;
                    break;
                }

                rankingListDetail.RankingListId = listid;
                rankingListDetail.Mark10 = Convert.ToDouble(rankingListDetail.Mark10);
                rankingListDetail.Mark4 = Convert.ToDouble(rankingListDetail.Mark4);

                db.RankingListDetails.Add(rankingListDetail);
            }

            db.SaveChanges();

            return Json(message);
        }

        public ActionResult ShowListForRanking(long id)
        {
            //Get clubId from Session
            var clubid = (long)Session["clubid"];

            return View(rankingService.GetListForRanking(id, clubid));
        }
    }
}

ClubHVNH/ClubHVNH/Controllers/PostController.cs
using ClubHVNH.Models;
using ClubHVNH.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ClubHVNH.Controllers
{
    public class PostController : Controller
    {
        private ClubManagementDbContext db = new ClubManagementDbContext();
        private readonly IPostService postService;

        //inject dependency
        public PostController(IPostService postService)
        {
            this.postService = postService;
        }

        [AuthorizeUser(AccessLevel = "HSV")]
        // GET: ProgramNotification
        public ActionResult Index()
        {
            return View(postService.GetPostsList());
        }

        [AuthorizeUser(AccessLevel = "HSV")]
        public ActionResult Create()
        {
            ViewBag.PostTypeId = new SelectList(db.PostTypes.ToList(), "Id", "Name");
            return View();
        }

        [AuthorizeUser(AccessLevel = "HSV")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "Id, Name, Description, Deadline, PostTypeId")] Post post)
        {
            if (ModelState.IsValid)
            {
                var createdate = DateTime.Now;
                post.CreatedDate = createdate;

                db.Posts.Add(post);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(post);
        }

        [AuthorizeUser(AccessLevel = "HSV")]
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var post = postService.GetPostInfo(id);

            if (post == null)
            {
                return HttpNotFound();
            }

            return View(post.FirstOrDefault());
        }

        [AuthorizeUser(AccessLevel = "HSV")]
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var post = db.Posts.Find(id);

            ViewBag.PostTypeId = new SelectList(db.PostTypes.ToList(), "Id", "Name", post.PostTypeId);

            if (post == null)
            {
                return HttpNotFound();
            }

            return View(post);
        }

        [AuthorizeUser(AccessLevel = "HSV")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Id, Name, Description, Deadline, PostTypeId")] Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(post);
        }

        [AuthorizeUser(AccessLevel = "HSV")]
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var post = postService.GetPostInfo(id);

            if (post == null)
            {
                return HttpNotFound();
            }

            return View(post.FirstOrDefault());
        }

        [AuthorizeUser(AccessLevel = "HSV")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            Post post = db.Posts.Find(id);

            db.Posts.Remove(post);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult NotificationDetails(long? id)
        {
            var clubid = (long)Session["clubid"];

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var post = postService.GetNotificationDetails(id, clubid);

            if (post == null)
            {
                return HttpNotFound();
            }

            ReadPost readPost = new ReadPost();

            readPost.PostId = Convert.ToInt32(post.Select(x => x.Id).FirstOrDefault());
            readPost.UserId = (long)Session["userid"];
            readPost.ReadTime = DateTime.Now;

            var readPostId = db.ReadPosts.Find(readPost.PostId, readPost.UserId);

            if(readPostId == null)
            {
                db.ReadPosts.Add(readPost);
                db.SaveChanges();
            }
            
            return View(post.FirstOrDefault());
        }

        [AuthorizeUser(AccessLevel = "HSV")]
        public ActionResult ListClubSent(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var list = postService.GetClubsSentList(id);

            if (list == null)
            {
                return HttpNotFound();
            }

            return View(list.ToList());
        }

        [AuthorizeUser(AccessLevel = "HSV")]
        public ActionResult ListMemberForProgram(long? id)
        {
            return View(postService.GetListMemberForProgram(id));
        }

        [AuthorizeUser(AccessLevel = "HSV")]
        public ActionResult ListMemberForRanking(long? listid, long? clubid)
        {
            return View(postService.GetListMemberForRanking(listid, clubid));
        }

        [AuthorizeUser(AccessLevel = "HSV")]
        [HttpPost]
        public JsonResult UpdateJoinedOrNot(List<JoinProgramDetail> joinProgramDetails)
        {
            string message = "ok";

            //Check for NULL.
            if (joinProgramDetails == null)
            {
                joinProgramDetails = new List<JoinProgramDetail>();
            }

            //Loop and insert records.
            foreach (var joinProgramDetail in joinProgramDetails)
            {
                var memberIsValid = db.Members.Find(joinProgramDetail.MemberId);

                if (memberIsValid == null)
                {
                    message = joinProgramDetail.MemberId;
                    break;
                }
                
                var memberId = joinProgramDetail.MemberId;
                var joinedOrNot = Convert.ToByte(joinProgramDetail.JoinedOrNot);
                var joinProgramListId = joinProgramDetail.JoinProgramListId;

                var list = db.JoinProgramDetails.Where(x => x.MemberId == memberId && x.JoinProgramListId == joinProgramListId).SingleOrDefault();

                if(list != null)
                {
                    list.JoinedOrNot = joinedOrNot;
                    db.Entry(list).State = EntityState.Modified;
                    db.SaveChanges();
                }

            }

            return Json(message);
        }
    }
}

ClubHVNH/ClubHVNH/Views/ListForRanking/Create.cshtml
@model IEnumerable<ClubHVNH.Models.ViewModel.MemberViewModel>

@{
    ViewBag.Title = "Gửi danh sách xếp loại thành viên";
}
<form method="post" id="insert_form">
    <div class="table-responsive">
        <table class="table">
            <thead>
                @{
                    int count = 0;
                }

                <tr>
                    <th>STT</th>
                    <th>@Html.DisplayNameFor(model => model.Id)</th>
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>@Html.DisplayNameFor(model => model.DateOfBirth)</th>
                    <th>@Html.DisplayNameFor(model => model.Class)</th>
                    <th>@Html.DisplayNameFor(model => model.Major)</th>
                    <th>@Html.DisplayNameFor(model => model.DepartmentName)</th>
                    <th>@Html.DisplayNameFor(model => model.RankName)</th>
                    <th>Mức độ đánh giá</th>
                    <th>Điểm hệ 10</th>
                    <th>Điểm hệ 4</th>
                </tr>
            </thead>

            <tbody id="item_table">
                @foreach (var item in Model)
                {

                    <tr>
                        <td>
                            @{ count++; }
                            @count
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.Id)</td>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.DateOfBirth)</td>
                        <td>@Html.DisplayFor(modelItem => item.Class)</td>
                        <td>@Html.DisplayFor(modelItem => item.Major)</td>
                        <td>@Html.DisplayFor(modelItem => item.DepartmentName)</td>
                        <td>@Html.DisplayFor(modelItem => item.RankName)</td>
                        <td>@Html.DropDownList("RankingCategoryId", null, htmlAttributes: new { @class = "form-control" })</td>
                        <td style="max-width:20px;"><input type="number" id="Mark10" name="Mark10" class="form-control" /></td>
                        <td style="max-width:20px;"><input type="number" id="Mark4" name="Mark4" class="form-control" /></td>
                    </tr>
                }
            </tbody>

            

        </table>
    </div>
</form>

<input type="button" id="btnSave" value="Gửi danh sách" class="btn btn-warning" />

<button class="btn btn-warning loading" type="button" disabled style="display:none;">
    <span class="glyphicon glyphicon-refresh"></span>
    Đang gửi...
</button>

<script type="text/javascript">
     $("#btnSave").on("click", function () {
        if (confirm("Bạn có chắc chắn muốn gửi danh sách?")) {

            //Loop through the Table rows and build a JSON array.
            var rankingListDetails = new Array();
            $("#item_table TR").each(function () {
                var row = $(this);
                var rankingListDetail = {};

                rankingListDetail.MemberId = row.find("TD").eq(1).html();
                rankingListDetail.RankingCategoryId = row.find("#RankingCategoryId").val();
                rankingListDetail.Mark10 = row.find("#Mark10").val();
                rankingListDetail.Mark4 = row.find("#Mark4").val();

                rankingListDetails.push(rankingListDetail);
            });

            $('.loading').show();
            $('#btnSave').hide();

            if (rankingListDetails.length === 0) {
                $('.loading').hide();
                $('#btnSave').show();

                alert("Danh sách đang trống");
            }

            else {
                var newUrl = '@Url.Action("Index", "ListForRanking")';

                //Send the JSON array to Controller using AJAX.
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Create", "ListForRanking")',
                    data: JSON.stringify(rankingListDetails),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",

                    success: function (message) {
                        if (message == 'ok') {
                            $('.loading').hide();
                            $('#btnSave').show();

                            alert("Danh sách đã được gửi");

                            window.location.href = newUrl;
                        }
                        else {
                            $('.loading').hide();
                            $('#btnSave').show();

                            alert("Mã sinh viên: " + message + " không tồn tại");
                        }

                    }
                });
            }
        }
    });

</script>

ClubHVNH/ClubHVNH/Views/ListForRanking/Index.cshtml
@model IEnumerable<ClubHVNH.Models.ViewModel.ProgramAndRankingViewModel>

@{
    ViewBag.Title = "Danh sách thông báo xếp loại thành viên";
}
<table class="table">

    @{
        int count = 0;
    }

    <tr>
        <th>STT</th>
        <th>@Html.DisplayNameFor(model => model.PostType)</th>
        <th>@Html.DisplayNameFor(model => model.Name)</th>
        <th>@Html.DisplayNameFor(model => model.Deadline)</th>
        <th>Trạng thái hạn nộp</th>
        <th>Trạng thái nộp</th>
        <th>Thao tác</th>
    </tr>

    @foreach (var item in Model)
    {

        <tr>
            <td>
                @{ count++; }
                @count
            </td>
            <td>@Html.DisplayFor(modelItem => item.PostType)</td>
            <td>@Html.DisplayFor(modelItem => item.Name)</td>
            <td>@Html.DisplayFor(modelItem => item.Deadline)</td>
            @{
                TimeSpan deadLineRange = Convert.ToDateTime(item.Deadline) - DateTime.Now;

                int deadLineValue = Convert.ToInt32(deadLineRange.TotalHours);

                if (deadLineValue >= 0)
                {
                    <td><span class="label label-success">Còn hạn</span></td>
                }

                else
                {
                    <td><span class="label label-danger">Hết hạn</span></td>
                }

                if (item.SentOrNot == "Gửi đúng hạn")
                {
                    <td><span class="label label-success">@item.SentOrNot</span></td>
                }

                else
                {
                    if (item.SentOrNot == "Gửi muộn")
                    {
                        <td><span class="label label-warning">@item.SentOrNot</span></td>
                    }

                    else
                    {
                        <td><span class="label label-danger">@item.SentOrNot</span></td>
                    }

                }
            }

            <td>@Html.ActionLink("Xem", "NotificationDetails", "Post", new { id = item.Id }, new { @class = "btn btn-primary" })</td>

            @{
                if (item.SentOrNot == "Gửi đúng hạn" || item.SentOrNot == "Gửi muộn")
                {
                    <td>@Html.ActionLink("Xem danh sách đã gửi", "ShowListForRanking", "ListForRanking", new { id = item.Id }, new { @class = "btn btn-success" })</td>
                }
            }
        </tr>
    }

</table>

ClubHVNH/ClubHVNH/Views/ListForRanking/ShowListForRanking.cshtml
@model IEnumerable<ClubHVNH.Models.ViewModel.ListForRankingViewModel>
@{
    ViewBag.Title = "Danh sách xếp loại thành viên";
}
<table class="table">

    @{
        int count = 0;
    }

    <tr>
        <th>STT</th>
        <th>@Html.DisplayNameFor(model => model.Id)</th>
        <th>@Html.DisplayNameFor(model => model.Name)</th>
        <th>@Html.DisplayNameFor(model => model.DateOfBirth)</th>
        <th>@Html.DisplayNameFor(model => model.Class)</th>
        <th>@Html.DisplayNameFor(model => model.Major)</th>
        <th>@Html.DisplayNameFor(model => model.DepartmentName)</th>
        <th>@Html.DisplayNameFor(model => model.RankName)</th>
        <th>@Html.DisplayNameFor(model => model.RankingCategory)</th>
        <th>@Html.DisplayNameFor(model => model.Mark10)</th>
        <th>@Html.DisplayNameFor(model => model.Mark4)</th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {

        <tr>
            <td>
                @{ count++; }
                @count
            </td>
            <td>@Html.DisplayFor(modelItem => item.Id)</td>
            <td>@Html.DisplayFor(modelItem => item.Name)</td>
            <td>@Html.DisplayFor(modelItem => item.DateOfBirth)</td>
            <td>@Html.DisplayFor(modelItem => item.Class)</td>
            <td>@Html.DisplayFor(modelItem => item.Major)</td>
            <td>@Html.DisplayFor(modelItem => item.DepartmentName)</td>
            <td>@Html.DisplayFor(modelItem => item.RankName)</td>
            <td>@Html.DisplayFor(modelItem => item.RankingCategory)</td>
            <td>@Html.DisplayFor(modelItem => item.Mark10)</td>
            <td>@Html.DisplayFor(modelItem => item.Mark4)</td>

        </tr>
    }

</table>